import type { AdminRole } from '@prisma/client'

export const adminPermissions = [
  'dashboard:view',
  'orders:view',
  'orders:create',
  'orders:update',
  'dining:view',
  'dining:update',
  'dining:sessions:close',
  'kitchen:view',
  'kitchen:update',
  'drivers:view',
  'drivers:self',
  'catalog:categories:view',
  'catalog:categories:manage',
  'catalog:products:view',
  'catalog:products:manage',
  'catalog:promotions:view',
  'catalog:promotions:manage',
  'catalog:coupons:view',
  'catalog:coupons:manage',
  'catalog:preview:view',
  'cash:view',
  'cash:manage',
  'payments:confirm',
  'history:view',
  'reports:view',
  'settings:store:view',
  'settings:store:manage',
  'settings:delivery:view',
  'settings:delivery:manage',
  'settings:preferences:view',
  'settings:preferences:manage',
  'users:view',
  'users:manage',
  'ai_attendant:view',
  'ai_attendant:manage',
  'printing:view',
  'printing:manage',
  'printing:reprint',
  'waiter:tables:view',
  'waiter:sessions:create',
  'waiter:orders:create',
  'waiter:orders:update',
  'waiter:orders:send',
  'waiter:orders:cancel_item',
  'waiter:items:deliver',
  'waiter:sessions:close_request',
  'waiter:tables:transfer',
] as const

export type AdminPermission = (typeof adminPermissions)[number]

const allPermissions = [...adminPermissions]

const rolePermissions: Record<AdminRole, AdminPermission[]> = {
  owner: allPermissions,
  manager: allPermissions.filter(
    (permission) =>
      !['settings:store:manage', 'users:manage'].includes(permission),
  ),
  attendant: [
    'dashboard:view',
    'orders:view',
    'orders:create',
    'orders:update',
    'dining:view',
    'catalog:categories:view',
    'catalog:products:view',
    'catalog:preview:view',
    'history:view',
  ],
  cashier: [
    'dashboard:view',
    'orders:view',
    'orders:create',
    'cash:view',
    'cash:manage',
    'payments:confirm',
    'dining:sessions:close',
    'history:view',
    'catalog:preview:view',
    'printing:view',
    'printing:reprint',
  ],
  kitchen: ['orders:view', 'orders:update', 'kitchen:view', 'kitchen:update'],
  waiter: [
    'waiter:tables:view',
    'waiter:sessions:create',
    'waiter:orders:create',
    'waiter:orders:update',
    'waiter:orders:send',
    'waiter:orders:cancel_item',
    'waiter:items:deliver',
    'waiter:sessions:close_request',
    'waiter:tables:transfer',
  ],
  driver: ['drivers:self'],
  supervisor: [
    'dashboard:view',
    'orders:view',
    'orders:create',
    'orders:update',
    'dining:view',
    'dining:update',
    'dining:sessions:close',
    'kitchen:view',
    'drivers:view',
    'catalog:categories:view',
    'catalog:products:view',
    'catalog:promotions:view',
    'catalog:coupons:view',
    'catalog:preview:view',
    'cash:view',
    'payments:confirm',
    'history:view',
    'reports:view',
    'settings:store:view',
    'settings:delivery:view',
    'settings:preferences:view',
    'users:view',
    'printing:view',
    'printing:reprint',
  ],
}

export function getPermissionsForRole(role: AdminRole): AdminPermission[] {
  return rolePermissions[role] ?? []
}
